POST http://localhost:3000/v1/user/signup
Content-Type: application/json

{
    "username": "khoale",
    "password": "12345",
    "fullname": "Lê Khoa"
}

###

POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
    "username": "khoale",
    "password": "12345"
}

###

